apiVersion: apps/v1
kind: Deployment
metadata:
  name: jubril-app
spec:
  selector:
    matchLabels:
      app: jubril-app
  replicas: 2
  template:
    metadata:
      labels:
        app: jubril-app
    spec:
      containers:
      - name: jubril-app-pods
        image: nanajanashia/argocd-app:1.1
        ports:
        - containerPort: 8080

